# Generated by Django 4.2.8 on 2023-12-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('subject1', models.CharField(max_length=50)),
                ('subject2', models.CharField(max_length=50)),
                ('subject3', models.CharField(max_length=50)),
                ('subject4', models.CharField(max_length=50)),
                ('subject5', models.CharField(max_length=50)),
                ('subject1_score', models.IntegerField()),
                ('subject2_score', models.IntegerField()),
                ('subject3_score', models.IntegerField()),
                ('subject4_score', models.IntegerField()),
                ('subject5_score', models.IntegerField()),
                ('image', models.ImageField(upload_to='student_images/')),
                ('class_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
            ],
        ),
    ]
